---
title: "Baseline_Analysis_TEMU"
author: "Alice Cade"
date: "01/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("tidyverse")
require("here")
require("readr")
library("plyr")
require("dplyr")
require("ggplot2")
require("lme4")
library(data.table)
library(rstatix)
library(emmeans)
require("performance")
require("insight")
require("magrittr")
library(see)
library(modelbased)
library("jtools")
require("kableExtra")
require("huxtable")
library(ggbeeswarm)
library("ggpubr")
library(reshape2)
require("WRS2")
library("ggExtra")
library("car")
```


### Baseline analysis for healthy, short-term, and long-term mTBI groups

Egocentric Localisation
Fixation
Pursuits
Saccades
Stroop
VOR

```{r cols, echo=FALSE}
myCols2 <- c("#D55E00", "#56B4E9")
myCols3 <- c("#56B4E9", "#009E73","#D55E00" )
myCols4 <- c("#D55E00","#009E73", "#56B4E9","#CC79A7")

#blue, green, orange , light blue  light green , light orange
myCols3LightDark <- c("#56B4E9", "#009E73","#D55E00", "#abd5ed" , "#b4dbd1",   "#e3b591")

myCols2LightDark <- c("#D55E00", "#56B4E9", "#e3b591", "#abd5ed")

```

## Egocentric Localisation

```{r EgoData, echo=FALSE, message=FALSE, warning=FALSE}
load("Ego_Healthy.Rda")
load("Ego_ShortTerm.Rda")
load("Ego_LongTerm.Rda")

Ego_Healthy$ID <- paste(Ego_Healthy$ID, 1, sep = "_")
Ego_ShortTerm$ID <- paste(Ego_ShortTerm$ID, 2, sep = "_")
Ego_LongTerm$ID <- paste(Ego_LongTerm$ID, 3, sep = "_")

EGOdf <- rbind(Ego_Healthy, Ego_ShortTerm, Ego_LongTerm)
save(EGOdf,file="EGOdf.Rda")


leveneTest(Error_X_mm ~ Pre_Post, EGOdf)
leveneTest(Error_Y_mm ~ Pre_Post, EGOdf) 
leveneTest(X_Shoot~ Pre_Post, EGOdf)
leveneTest(Y_Shoot~ Pre_Post, EGOdf)

shapiro.test(EGOdf$Error_X_mm)
shapiro.test(EGOdf$Error_Y_mm)
shapiro.test(EGOdf$X_Shoot)
shapiro.test(EGOdf$Y_Shoot)

colNames <- c("ID","Trial Number",  "Horizontal Error (mm)", "Vertical Error (mm)","Horizontal Overshoots", "Vertical Overshoots", "Pre_Post", "TBI_Non")
testTitle <- "Summary Data for Egocentric Localisation"
source("GetSummaryTables.R")
GetSummaryTablesCIs(EGOdf, colNames, testTitle) 
```


```{r Visualise_Ego, echo=FALSE}
# Nice graphic for showing postion head to targ
library(png)
library(grid)
img <- readPNG("Transp_Targ.png")
g <- rasterGrob(img, width=unit(0.1,"npc"), height=unit(0.13,"npc"), interpolate = FALSE)


EGOdf_VIS <-  EGOdf
EGOdf_VIS$TBI_Non <- gsub('Non', 'Healthy',   EGOdf_VIS$TBI_Non)
EGOdf_VIS$TBI_Non <- gsub('Short', 'mTBI',   EGOdf_VIS$TBI_Non)
EGOdf_VIS$TBI_Non <- gsub( 'Long', 'PPCS', EGOdf_VIS$TBI_Non)
EGO_Vis <- ggplot(EGOdf_VIS, aes(Error_X_mm, Error_Y_mm), show.legend = FALSE ) +
  annotation_custom(rasterGrob(img, interpolate = T), xmin = -30, xmax=30, ymin = -30, ymax=30)  +
  xlab("Horizontal error (mm)") + ylab("Vertical error (mm)")  + #
  geom_point(aes(colour=fct_rev(TBI_Non)), alpha = 0.4, show.legend = FALSE ) + #, shape=Pre_Post
  theme_minimal() +
  geom_density_2d( aes(color = TBI_Non), alpha = 0.6,bins = 10 , show.legend = FALSE) + #
  #stat_density_2d_filled( aes(color = fct_rev(TBI_Non)), alpha = 0.5,bins = 10 , show.legend = FALSE) + #
  facet_grid(~ TBI_Non ) +
  theme(aspect.ratio = 1)
ggsave("EGO_Vis.png", width = 20, height = 7, units = "cm")

```

```{r EgoModel_X, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(Error_X_mm ~ TBI_Non, data = EGOdf)

diffs <- EGOdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Error_X_mm, na.rm = T), Mean = mean(Error_X_mm, na.rm = T), SD = sd(Error_X_mm, na.rm = T))

stat.test <- compare_means(
 Error_X_mm ~ TBI_Non, data = EGOdf,
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(250, 300, 350))

H_Ego <- ggplot(EGOdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = Error_X_mm, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Horizontal error (mm)")+
  geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 5) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=16)) 

```



```{r EgoModel_Y, echo=FALSE}
K_test_Pres <-  kruskal.test(Error_Y_mm ~ TBI_Non, data = EGOdf)

diffs <- EGOdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Error_Y_mm, na.rm = T), Mean = mean(Error_Y_mm, na.rm = T), SD = sd(Error_Y_mm, na.rm = T))


stat.test <- compare_means(
 Error_Y_mm ~ TBI_Non, data = EGOdf,
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(250, 300, 350))

V_Ego <- ggplot(EGOdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   Error_Y_mm, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Vertical error (mm)")+
  geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 5) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=16))  
ggsave("V_Ego.png", width = 10, height = 11, units = "cm")



EgoPlots <- ggarrange(H_Ego, V_Ego, labels = c("A", "B") ) 
ggsave("EgoPlots.png", width = 30, height = 15, units = "cm")
```


```{r Ego_Shoots, echo=FALSE}
# still over and undershooting?
X_Shoots <- EGOdf#EGOdf[c(1,7)]
X_Shoots$X_Under <- ifelse(X_Shoots$X_Shoot > 0, 0, 1)
colnames(X_Shoots)[4] <- "X_Over"

PropXOver <- X_Shoots %>% group_by(ID) %>%
  dplyr::summarise(PropPos = mean(X_Over), CorrSD = sd(X_Over), Num = n(), CorrSE = CorrSD/n())
PropXUnder <- X_Shoots %>% group_by(ID) %>%
  dplyr::summarise(PropPos = mean(X_Under), CorrSD = sd(X_Under), Num = n(), CorrSE = CorrSD/n())

Overs <- data.frame(over=PropXOver$PropPos)
Unders <- data.frame(under=PropXUnder$PropPos)
Over_UnderX <- cbind(Overs, Unders)
Over_UnderX <- Over_UnderX %>% gather(Ov_Und, PropPosition, "over","under") 
ggplot(Over_UnderX, aes(PropPosition, fill = Ov_Und)) + geom_density(alpha = 0.2) + scale_fill_manual(values=myCols2)
#X_Axis <- prop.test(x=c(sum(X_Shoots$X_Over), sum(X_Shoots$X_Under)), n = c(nrow(X_Shoots), nrow(X_Shoots)), alternative = "less")
#X_Axis
# Y over/under
Y_Shoots <- EGOdf
Y_Shoots$Y_Under <- ifelse(Y_Shoots$Y_Shoot > 0, 0, 1)  
colnames(Y_Shoots)[5] <- "Y_Over"
PropYOver <- Y_Shoots %>% group_by(ID) %>%
  dplyr::summarise(PropPos = mean(Y_Over), CorrSD = sd(Y_Over), Num = n(), CorrSE = CorrSD/n())
PropYUnder <- Y_Shoots %>% group_by(ID) %>%
  dplyr::summarise(PropPos = mean(Y_Under), CorrSD = sd(Y_Under), Num = n(), CorrSE = CorrSD/n())

Overs <- data.frame(over=PropYOver$PropPos)
Unders <- data.frame(under=PropYUnder$PropPos)
Over_UnderY <- cbind(Overs, Unders)
Over_UnderY <- Over_UnderY %>% gather(Ov_Und, PropPosition, "over","under") 
ggplot(Over_UnderY, aes(PropPosition, fill = Ov_Und)) + geom_density(alpha = 0.2) + scale_fill_manual(values=myCols2)
#Y_Axis <- prop.test(x=c(sum(Y_Shoots$Y_Over), sum(Y_Shoots$Y_Under)), n = c(nrow(Y_Shoots), nrow(Y_Shoots)))
#Y_Axis


# Diff Bw TBI and non for X undershoots?
PropXUnderTBI <- X_Shoots %>% group_by(TBI_Non) %>%
  dplyr::summarise(PropPos = mean(X_Under), CorrSD = sd(X_Under), Num = n(), CorrSE = CorrSD/115) # Make n number of partic not 



PropXUnderTBI$TBI_Non <- factor(PropXUnderTBI$TBI_Non, levels = c("Non", "Short", "Long"))
X_OverPlot <- ggplot(PropXUnderTBI  ) + geom_col(aes(x=TBI_Non, y=PropPos), fill=myCols3, alpha = 0.7) + geom_errorbar(aes(x = TBI_Non, ymin = PropPos-CorrSE*1.96, ymax = PropPos + CorrSE*1.96), width=.2, position=position_dodge(.9)) + 
  labs(x = "", y = "Proportion horizontal hndershoots") + geom_hline(aes(slope = 0, yintercept = 0.5), linetype="dashed" ) +
  theme_minimal() + scale_x_discrete(labels=c("Non" = "Control", "Short" = "mTBI", "Long"= "PPCS")) + ylim(0,1) + theme(text = element_text(size = 20)) 


# Diff Bw TBI and non for X undershoots?
PropXUnderTots <- X_Shoots %>% group_by(TBI_Non) %>%
  dplyr::summarise(Tot = sum(X_Under), PropPos = mean(X_Under), CorrSD = sd(X_Under), Num = n(), CorrSE = CorrSD/115) # Make n number of partic not 

library("DescTools") # This package masks %like% detatch after use
BinomCI1 <- BinomCI(x=PropXUnderTots$Tot, n=PropXUnderTots$Num, method="jeffreys", sides="two.sided")
PropXUnderTots <- cbind(PropXUnderTots, BinomCI1)
#detach("package:DescTools")

PropXUnderTots <-PropXUnderTots %>% add_row(TBI_Non="Long", Tot= (PropXUnderTots$Num[1]-PropXUnderTots$Tot[1]),PropPos=((PropXUnderTots$Num[1]-PropXUnderTots$Tot[1]) /PropXUnderTots$Num[1]), CorrSD=NA, Num=PropXUnderTots$Num[1], CorrSE=NA)
PropXUnderTots <-PropXUnderTots %>% add_row(TBI_Non="Non", Tot= (PropXUnderTots$Num[2] - PropXUnderTots$Tot[2]),PropPos=(PropXUnderTots$Num[2]-PropXUnderTots$Tot[2]) / PropXUnderTots$Num[2], CorrSD=NA, Num=PropXUnderTots$Num[2], CorrSE=NA)
PropXUnderTots <-PropXUnderTots %>% add_row(TBI_Non="Short", Tot= (PropXUnderTots$Num[3] - PropXUnderTots$Tot[3]),PropPos=(PropXUnderTots$Num[3]-PropXUnderTots$Tot[3]) / PropXUnderTots$Num[3], CorrSD=NA, Num=PropXUnderTots$Num[3], CorrSE=NA)

# non = blue
#short = green
#long = red

myCols3LightDarkMIX <- c("#D55E00","#56B4E9", "#009E73",     "#e3b591", "#abd5ed" ,"#b4dbd1")

PropXUnderTots$TBI_Non <- factor(PropXUnderTots$TBI_Non, levels = c("Non", "Short", "Long"))
X_OverPlot <- ggplot(PropXUnderTots) + geom_col(aes(x=TBI_Non, y=(PropPos*100)), fill=myCols3LightDarkMIX, alpha = 0.7) + geom_errorbar(aes(x = TBI_Non, ymin = (lwr.ci*100), ymax = (upr.ci*100)), width=.2,
                 position=position_dodge(.9))  + labs(x = " ", y = "Percentage horizontal undershoots") + 
  geom_hline(aes(slope = 0, yintercept = 50), linetype="dashed" ) + theme_classic() + ylim(0,100)+
  scale_x_discrete(labels=c("Non" = "Control", "Short" = "mTBI", "Long"= "PPCS")) + theme(text = element_text(size = 20)) 


# differences bw groups
propX_TBI <- prop.test(x=c((PropXUnderTBI$Num[1] * PropXUnderTBI$PropPos[1]),(PropXUnderTBI$Num[2] * PropXUnderTBI$PropPos[2]), (PropXUnderTBI$Num[3] * PropXUnderTBI$PropPos[3])),n=c(PropXUnderTBI$Num[1],PropXUnderTBI$Num[2] ,PropXUnderTBI$Num[3])) 


# Diff Bw TBI and non for Y undershoots?
PropYUnderTots <- Y_Shoots %>% group_by(TBI_Non) %>%
  dplyr::summarise(Tot = sum(Y_Under), PropPos = mean(Y_Under), CorrSD = sd(Y_Under), Num = n(), CorrSE = CorrSD/115) # Make n number of partic not 

library("DescTools") # This package masks %like% detatch after use
BinomCI1 <- BinomCI(x=PropYUnderTots$Tot, n=PropYUnderTots$Num, method="jeffreys", sides="two.sided")
PropYUnderTots <- cbind(PropYUnderTots, BinomCI1)
detach("package:DescTools")

PropYUnderTots <-PropYUnderTots %>% add_row(TBI_Non="Long", Tot= (PropYUnderTots$Num[1]-PropYUnderTots$Tot[1]),PropPos=((PropYUnderTots$Num[1]-PropYUnderTots$Tot[1]) /PropYUnderTots$Num[1]), CorrSD=NA, Num=PropYUnderTots$Num[1], CorrSE=NA)
PropYUnderTots <-PropYUnderTots %>% add_row(TBI_Non="Non", Tot= (PropYUnderTots$Num[2] - PropYUnderTots$Tot[2]),PropPos=(PropYUnderTots$Num[2]-PropYUnderTots$Tot[2]) / PropYUnderTots$Num[2], CorrSD=NA, Num=PropYUnderTots$Num[2], CorrSE=NA)
PropYUnderTots <-PropYUnderTots %>% add_row(TBI_Non="Short", Tot= (PropYUnderTots$Num[3] - PropYUnderTots$Tot[3]),PropPos=(PropYUnderTots$Num[3]-PropYUnderTots$Tot[3]) / PropYUnderTots$Num[3], CorrSD=NA, Num=PropYUnderTots$Num[3], CorrSE=NA)

PropYUnderTots$TBI_Non <- factor(PropYUnderTots$TBI_Non, levels = c("Non", "Short", "Long"))
Y_OverPlot <- ggplot(PropYUnderTots) + geom_col(aes(x=TBI_Non, y=(PropPos*100)), fill=myCols3LightDarkMIX, alpha = 0.7) + geom_errorbar(aes(x = TBI_Non, ymin = (lwr.ci*100), ymax = (upr.ci*100)), width=.2,
                 position=position_dodge(.9))  + labs(x = " ", y = "Percentage vertical undershoots") + 
  geom_hline(aes(slope = 0, yintercept = 50), linetype="dashed" ) + theme_classic() + ylim(0,100)+
  scale_x_discrete(labels=c("Non" = "Control", "Short" = "mTBI", "Long"= "PPCS"))+ theme(text = element_text(size = 20)) 



propY_TBI <- prop.test(x=c((PropYUnderTBI$Num[1] * PropYUnderTBI$PropPos[1]),(PropYUnderTBI$Num[2] * PropYUnderTBI$PropPos[2]),(PropYUnderTBI$Num[3] * PropYUnderTBI$PropPos[3])),n=c(PropYUnderTBI$Num[1],PropYUnderTBI$Num[2],PropYUnderTBI$Num[3] )) 

EgoOverPlots <- ggarrange(X_OverPlot, Y_OverPlot, labels = c("A", "B") ) 
ggsave("EgoOverPlots.png", width = 30, height = 15, units = "cm")

```

## Fixation

```{r FixData, echo=FALSE, message=FALSE, warning=FALSE}
load("Fix_Healthy.Rda")
load("Fix_ShortTerm.Rda")
load("Fix_LongTerm.Rda")

#view(Fix_Healthy)
#view(Fix_ShortTerm)
#view(Fix_LongTerm)

Fix_Healthy$ID <- paste(Fix_Healthy$ID, 1, sep = "_")
Fix_Healthy$BCEA_68_Log10 <- log10(Fix_Healthy$BCEA_68_degsq)
Fix_Healthy <- Fix_Healthy[c(1,2,4:8)]
Fix_ShortTerm$ID <- paste(Fix_ShortTerm$ID, 2, sep = "_")
Fix_LongTerm$ID <- paste(Fix_LongTerm$ID, 3, sep = "_")
FIXdf <- rbind(Fix_Healthy, Fix_ShortTerm, Fix_LongTerm)
save(FIXdf,file="FIXdf.Rda")

Fix_LongTerm$BCEA_68_Log10

leveneTest(HVA_Mean_deg ~ Pre_Post, FIXdf)
leveneTest(VVA_Mean_deg ~ Pre_Post, FIXdf) 
leveneTest(BCEA_68_Log10 ~ Pre_Post, FIXdf)

shapiro.test(FIXdf$HVA_Mean_deg)
shapiro.test(FIXdf$VVA_Mean_deg)
shapiro.test(FIXdf$BCEA_68_Log10)


colNames <- c("ID","Trial Number", "Horizontal Visual Angle Error (deg)", "Vertical Visual Angle Error (deg)",  "Pre_Post", "TBI_Non","BCEA Log10 (MinArc2)")
testTitle <- "Summary Data for Fixation"
source("GetSummaryTables.R")
GetSummaryTablesCIs(FIXdf, colNames, testTitle) 
```

```{r FIXModel_X, echo=FALSE, message=FALSE, warning=FALSE }
# difference bw Pre groups
K_test_Pres <-  kruskal.test(HVA_Mean_deg ~ TBI_Non, data = FIXdf)
diffs <- FIXdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(HVA_Mean_deg, na.rm = T), Mean = mean(HVA_Mean_deg, na.rm = T), SD = sd(HVA_Mean_deg, na.rm = T))

stat.test <- compare_means(
 HVA_Mean_deg ~ TBI_Non, data = FIXdf,
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(1, 1.3, 1.8))

H_Fix <- ggplot(FIXdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   HVA_Mean_deg, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Horizontal visual angle error (degrees)")+
  geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 5) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=16))  
```
```{r FIXModel_Y, echo=FALSE, message=FALSE, warning=FALSE }
# difference bw Pre groups
K_test_Pres <-  kruskal.test(VVA_Mean_deg ~ TBI_Non, data = FIXdf)
diffs <- FIXdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(VVA_Mean_deg, na.rm = T), Mean = mean(VVA_Mean_deg, na.rm = T), SD = sd(VVA_Mean_deg, na.rm = T))

stat.test <- compare_means(
 VVA_Mean_deg ~ TBI_Non, data = FIXdf,
 method = "wilcox.test"#, p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(1.5, 1.8, 2.2))


V_Fix <- ggplot(FIXdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   VVA_Mean_deg, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Vertical Visual Angle Error (degrees)")+
  geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 5) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=16))  
FixXYPlots <- ggarrange(  H_Fix, V_Fix, labels = c( "A" ,"B"))
ggsave("FixPlots.png", width = 20, height = 13, units = "cm")
```

```{r FIX_BCEA, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(BCEA_68_Log10 ~ TBI_Non, data = FIXdf)
diffs <- FIXdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(BCEA_68_Log10, na.rm = T), Mean = mean(BCEA_68_Log10, na.rm = T), SD = sd(BCEA_68_Log10, na.rm = T))

stat.test <- compare_means(
 BCEA_68_Log10 ~ TBI_Non, data = FIXdf,
 method = "wilcox.test"#, p.adjust.method = "holm"
)

stat.test <- stat.test %>%
 mutate(y.position = c(5, 5.5, 6))

test <-  expression("BCEA log"[10]* " (minarc"^2*")")
my_title <- parse(text=test)

B_Fix <- ggplot(FIXdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   BCEA_68_Log10, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab(my_title)+
  #geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 5) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=16))  

FixPlots <- ggarrange(B_Fix, NULL,   H_Fix, V_Fix, labels = c( "A" ,"", "B", "C"))
ggsave("FixPlots.png", width = 30, height = 25, units = "cm")
```

## Pursuits

```{r PurData, echo=FALSE, message=FALSE, warning=FALSE}
load("Pur_Healthy.Rda")
load("Pur_ShortTerm.Rda")
load("Pur_LongTerm.Rda")

Pur_Healthy$ID <- paste(Pur_Healthy$ID, 1, sep = "_")
Pur_ShortTerm$ID <- paste(Pur_ShortTerm$ID, 2, sep = "_")
Pur_LongTerm$ID <- paste(Pur_LongTerm$ID, 3, sep = "_")
Pur_LongTerm <- Pur_LongTerm[-c(9,10)]
PURdf <- rbind(Pur_Healthy, Pur_ShortTerm, Pur_LongTerm)
save(PURdf,file="PURdf.Rda")


leveneTest(Num_Sacs ~ Pre_Post, PURdf)
leveneTest(HVA_Error_Mean_deg ~ Pre_Post, PURdf) 
leveneTest(VVA_Error_Mean_deg ~ Pre_Post, PURdf)
leveneTest(TotalVA_Error_Mean_deg ~ Pre_Post ,PURdf)
leveneTest(Gain_Total ~ Pre_Post, PURdf)
leveneTest(Gain_Horiz ~ Pre_Post, PURdf)
leveneTest(Gain_Vert ~ Pre_Post, PURdf)

shapiro.test(PURdf$Num_Sacs)
shapiro.test(PURdf$HVA_Error_Mean_deg)
shapiro.test(PURdf$VVA_Error_Mean_deg)
shapiro.test(PURdf$TotalVA_Error_Mean_deg)
shapiro.test(PURdf$Gain_Total)
shapiro.test(PURdf$Gain_Horiz)
shapiro.test(PURdf$Gain_Vert)

colNames <- c("ID","Trial Number", "Number of Saccades", "Horizontal Visual Angle Error (deg)", "Vertical Visual Angle Error (deg)","Total Visual Angle Error (deg)", "Total Gain", "Horizontal Gain", "Vertical Gain", "Pre_Post", "TBI_Non")
testTitle <- "Summary Data for Pursuits"
source("GetSummaryTables.R")
GetSummaryTablesCIs(PURdf, colNames, testTitle) 

PURdf$Num_Sacs
# percental horzont saccs
r_Full <- nrow(PURdf)
n_H_Sac <- nrow(subset(PURdf, Num_Sacs >= 1))
N_Hor_Sac <- (n_H_Sac/r_Full)*100
N_Hor_Sac

r_Full_Non <- nrow(subset(PURdf, TBI_Non %like% "Non"))
n_H_Sac_Non <- nrow(subset(subset(PURdf, TBI_Non %like% "Non"), Num_Sacs >= 1))
N_Hor_Sac_Non <- (n_H_Sac_Non/r_Full_Non)*100
N_Hor_Sac_Non

r_Full_TBI <- nrow(subset(PURdf, TBI_Non %like% "Short"))
n_H_Sac_TBI <- nrow(subset(subset(PURdf, TBI_Non %like% "Short"), Num_Sacs >= 1))
N_Hor_Sac_TBI <- (n_H_Sac_TBI/r_Full_TBI)*100
N_Hor_Sac_TBI

r_Full_PCS <- nrow(subset(PURdf, TBI_Non %like% "Long"))
n_H_Sac_PCS <- nrow(subset(subset(PURdf, TBI_Non %like% "Long"), Num_Sacs >= 1))
N_Hor_Sac_PCS <- (n_H_Sac_PCS/r_Full_PCS)*100
N_Hor_Sac_PCS

NumSacsGroup <- chisq.test(x=c(N_Hor_Sac_Non, N_Hor_Sac_TBI, N_Hor_Sac_PCS), p = c(1/3, 1/3, 1/3))
```

```{r T_Pur, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(TotalVA_Error_Mean_deg ~ TBI_Non, data = PURdf)
diffs <- PURdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(TotalVA_Error_Mean_deg, na.rm = T), Mean = mean(TotalVA_Error_Mean_deg, na.rm = T), SD = sd(TotalVA_Error_Mean_deg, na.rm = T))

stat.test <- compare_means(
 TotalVA_Error_Mean_deg ~ TBI_Non, data = PURdf, method = "t.test", p.adjust.method = "holm")#
stat.test <- stat.test %>%
 mutate(y.position = c(0.8, 1, 1.3))

T_Pur <- ggplot(PURdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = TotalVA_Error_Mean_deg, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Total visual angle error (degrees)")+
  geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=14))  

```

```{r H_Pur, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(HVA_Error_Mean_deg ~ TBI_Non, data = PURdf)
diffs <- PURdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(HVA_Error_Mean_deg, na.rm = T), Mean = mean(HVA_Error_Mean_deg, na.rm = T), SD = sd(HVA_Error_Mean_deg, na.rm = T))

stat.test <- compare_means(
 HVA_Error_Mean_deg ~ TBI_Non, data = PURdf, method = "wilcox.test", p.adjust.method = "holm")
stat.test <- stat.test %>%
 mutate(y.position = c( 1.3, 1.6, 1.9))

H_Pur <- ggplot(PURdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = HVA_Error_Mean_deg, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Horizontal visual angle error (degrees)")+
  geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=14)) 
```

```{r V_Pur, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(VVA_Error_Mean_deg ~ TBI_Non, data = PURdf)
diffs <- PURdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(VVA_Error_Mean_deg, na.rm = T), Mean = mean(VVA_Error_Mean_deg, na.rm = T), SD = sd(VVA_Error_Mean_deg, na.rm = T))


stat.test <- compare_means(
 VVA_Error_Mean_deg ~ TBI_Non, data = PURdf, method = "wilcox.test", p.adjust.method = "holm")
stat.test <- stat.test %>%
 mutate(y.position = c( 2.8, 3.2, 3.7))

V_Pur <- ggplot(PURdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = VVA_Error_Mean_deg, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Vertical visual angle error (degrees)")+
  geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=14)) 
PurPlots <- ggarrange(T_Pur, NULL,   H_Pur, V_Pur, labels = c( "A" ,"", "B", "C"))
ggsave("PurPlots.png", width = 22, height = 22, units = "cm")

```

```{r T_Gain, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(Gain_Total ~ TBI_Non, data = PURdf)
diffs <- PURdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Gain_Total, na.rm = T), Mean = mean(Gain_Total, na.rm = T), SD = sd(Gain_Total, na.rm = T))

stat.test <- compare_means(
 Gain_Total ~ TBI_Non, data = PURdf, method = "wilcox.test", p.adjust.method = "holm")#
stat.test <- stat.test %>%
 mutate(y.position = c(1.1, 1.15,1.2))

T_Gain <- ggplot(PURdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = Gain_Total, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Total gain")+
  geom_hline(yintercept=1, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=14)) 

PurPlots4 <- ggarrange(T_Pur,  H_Pur, V_Pur,T_Gain, labels = c( "A" , "B", "C", "D"))
ggsave("PurPlots4.png", width = 22, height = 22, units = "cm")
```

```{r H_Gain, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(Gain_Horiz ~ TBI_Non, data = PURdf)
diffs <- PURdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Gain_Horiz, na.rm = T), Mean = mean(Gain_Horiz, na.rm = T), SD = sd(Gain_Horiz, na.rm = T))


stat.test <- compare_means(
 Gain_Horiz ~ TBI_Non, data = PURdf, method = "wilcox.test", p.adjust.method = "holm")#
stat.test <- stat.test %>%
 mutate(y.position = c(1.8, 1.9,2))

H_Gain <- ggplot(PURdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = Gain_Horiz, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Horizontal gain")+
  geom_hline(yintercept=1, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=14)) 

```

```{r V_Gain, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(Gain_Vert ~ TBI_Non, data = PURdf)
diffs <- PURdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Gain_Vert, na.rm = T), Mean = mean(Gain_Vert, na.rm = T), SD = sd(Gain_Vert, na.rm = T))


stat.test <- compare_means(
 Gain_Vert ~ TBI_Non, data = PURdf, method = "wilcox.test", p.adjust.method = "holm")#
stat.test <- stat.test %>%
 mutate(y.position = c(1.8, 1.9,2.05))

V_Gain <- ggplot(PURdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = Gain_Vert, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Vertical gain")+
  geom_hline(yintercept=1, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=14)) 

```

```{r N_Sacs, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(Num_Sacs ~ TBI_Non, data = PURdf)
diffs <- PURdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Num_Sacs, na.rm = T), Mean = mean(Num_Sacs, na.rm = T), SD = sd(Num_Sacs, na.rm = T))


stat.test <- compare_means(
 Num_Sacs ~ TBI_Non, data = PURdf, method = "wilcox.test", p.adjust.method = "holm")#
stat.test <- stat.test %>%
 mutate(y.position = c(4,6,8))

N_Sacs <- ggplot(PURdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = Num_Sacs, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, width = 0.1, height=0, alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Number of saccades")+
  #geom_hline(yintercept=1, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 18)) + 
     theme(axis.title=element_text(size=14)) 




Control  <- subset(PURdf, TBI_Non %like% "Non")
Control  <- Control$Num_Sacs
Control <- as.data.frame(table(Control))
Control$Non <- (Control$Freq / sum(Control$Freq))*100
mTBI <- subset(PURdf,  TBI_Non %like% "Short")
mTBI <-  mTBI$Num_Sacs
mTBI <- as.data.frame(table(mTBI))
mTBI$Short <- (mTBI$Freq / sum(mTBI$Freq))*100  
PPCS  <- subset(PURdf,  TBI_Non %like% "Long")
PPCS  <- PPCS$Num_Sacs
PPCS <- as.data.frame(table(PPCS))
PPCS$Long <- (PPCS$Freq / sum(PPCS$Freq))*100 


Outcome_Change <- qpcR:::cbind.na(Control, mTBI, PPCS)
Outcome_Change <- as.data.frame(Outcome_Change)
Outcome_ChangeG <- Outcome_Change %>% gather(State, NumberS, 3,6,9)
Outcome_ChangeG$NumberS[is.na(Outcome_ChangeG$NumberS)]<-0
#Outcome_ChangeG$NumberS <- round(Outcome_ChangeG$NumberS, 0)
Outcome_ChangeG$Count <- seq(0,8, by=1)

myColsLightDark <- c("#D55E00","#f2b483", "#56B4E9", "#aad8f2")

myColsLightDark <- c( 'darkorange','#f2b483', 'dodgerblue', '#aad8f2')

myCols6 <- c(  'dodgerblue','#aad8f2', '#64d40b','#b8f587' ,'#f2b483','darkorange')

myCols9 <- c("red", '#9d2ef2', 'blue', 'dodgerblue','#aad8f2', '#64d40b','#b8f587' ,'#f2b483','darkorange')

Outcome_ChangeG$TBI_Non <- as.factor(Outcome_ChangeG$State)
Outcome_ChangeG$Count <- as.factor(Outcome_ChangeG$Count)

Outcome_ChangeG <- Outcome_ChangeG[c(8,9, 10)]


stat.test$Count <- as.factor(0)
stat.test <- stat.test %>%
 mutate(y.position = c(112,124, 136))
Pur_Stacked <- ggplot(Outcome_ChangeG , aes( y=NumberS, x=TBI_Non,fill=fct_rev(Count))) + 
    geom_bar( stat="identity")+
  theme_classic() + xlab("") + ylab("Percentage") + guides(fill = guide_legend(reverse = T)) + 
  theme( legend.position = "right") +
  labs(fill = "Number of\nsaccades")  +   scale_fill_manual( values = myCols9) + 
     theme(axis.title=element_text(size=12)) + 
  scale_y_continuous(breaks=seq(0,100,20))+
  scale_x_discrete(limits=c("Non","Short" , "Long" ), labels=c("Non" = "Control", "Short" = "mTBI","Long" = "PPCS" )) + stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) + theme(legend.title = element_text(size=12)) 
  
  






PurPlotsGain <- ggarrange(T_Gain , H_Gain, V_Gain, Pur_Stacked, ncol=2, nrow=2, labels = c( "A" ,"B", "C", "D"))
ggsave("PurPlotsGain.png", width = 25, height = 22, units = "cm")
```

## Saccades

```{r SacData, echo=FALSE, message=FALSE, warning=FALSE}
load("Sac_Healthy.Rda")
load("Sac_ShortTerm.Rda")
load("Sac_LongTerm.Rda")

view(Sac_Healthy)
view(Sac_ShortTerm)
view(Sac_LongTerm)

Sac_Healthy$ID <- paste(Sac_Healthy$ID, 1, sep = "_")
colnames(Sac_Healthy)[colnames(Sac_Healthy) == 'Test_Corr' ] <- 'Test_Corr_R'
Sac_Healthy <- Sac_Healthy[-c(4,5,6,9)]
Sac_ShortTerm$ID <- paste(Sac_ShortTerm$ID, 2, sep = "_")
Sac_ShortTerm <- Sac_ShortTerm[-c(2,4)]
Sac_LongTerm$ID <- paste(Sac_LongTerm$ID, 3, sep = "_")
Sac_LongTerm <- Sac_LongTerm[-c(2,4,6)]
SACdf <- rbind(Sac_Healthy, Sac_ShortTerm, Sac_LongTerm)
save(SACdf,file="SACdf.Rda")


#leveneTest(Test_Corr_R ~ Pre_Post,       SACdf)
#leveneTest(Saccade_Latency ~ Pre_Post,   SACdf) 
#leveneTest(Saccade_Vel_Deg_s ~ Pre_Post, SACdf)


shapiro.test(SACdf$Test_Corr_R)
shapiro.test(SACdf$Saccade_Latency)
shapiro.test(SACdf$Saccade_Vel_Deg_s)


colNames <- c("ID", "Target Type" ,"Number Trials Correct", "Saccade Latency (s)", "Saccade Velocity (deg/s)", "TBI_Non")
testTitle <- "Summary Data for Saccades"
source("GetSummaryTables.R")
GetSummaryTablesCIs(SACdf, colNames, testTitle) 
```

```{r Sac_Trials Corr, echo=FALSE, message=FALSE, warning=FALSE }
## Pro Sac
K_test_Pres <-  kruskal_test(Test_Corr_R ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "ProSac"))
diffs <- subset(SACdf, TargType_Unity %like% "ProSac") %>% group_by(TBI_Non) %>%
  dplyr::summarise(Tot = sum(Test_Corr_R, na.rm = T), Medians = median(Test_Corr_R, na.rm = T), Mean = mean(Test_Corr_R, na.rm = T), Percentage=(mean(Test_Corr_R, na.rm = T)*100), SD = sd(Test_Corr_R, na.rm = T), Num = n(), CorrSE = SD/115)


library("DescTools") # This package masks %like% detatch after use
BinomCI1 <- BinomCI(x=diffs$Tot, n=diffs$Num, method="jeffreys", sides="two.sided")
diffs <- cbind(diffs, BinomCI1)
#detach("package:DescTools")


stat.test <- compare_means(
 Test_Corr_R ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "ProSac"),
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(92, 100, 110))

PT_Sac <- ggbarplot(diffs, x = "TBI_Non", y = "Percentage", 
          color = "white",alpha = 0.7, fill = "TBI_Non", palette = myCols3,  alpha = 0.7,  #add = "jitter",
          width=0.9,
          order = c("Non", "Short", "Long"),
          ylab = "Percentage correct pro-saccade trials", xlab = " ") + 
          scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  geom_errorbar(aes(x= TBI_Non, ymin= (lwr.ci*100), ymax = (upr.ci*100)), width=.2, position=position_dodge(.9)) +
          theme(legend.position = "none")+
    stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 12)) + 
     theme(axis.title=element_text(size=12))
   #labs( subtitle = get_test_label(K_test_Pres, detailed = TRUE))


## Anti Sac
K_test_Pres <-  kruskal_test(Test_Corr_R ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "AntiSac"))

diffs <- subset(SACdf, TargType_Unity %like% "AntiSac") %>% group_by(TBI_Non) %>%
  dplyr::summarise(Tot = sum(Test_Corr_R, na.rm = T), Medians = median(Test_Corr_R, na.rm = T), Mean = mean(Test_Corr_R, na.rm = T), Percentage=(mean(Test_Corr_R, na.rm = T)*100), SD = sd(Test_Corr_R, na.rm = T), Num = n(), CorrSE = SD/115)

library("DescTools") # This package masks %like% detatch after use
BinomCI1 <- BinomCI(x=diffs$Tot, n=diffs$Num, method="jeffreys", sides="two.sided")
diffs <- cbind(diffs, BinomCI1)
detach("package:DescTools")


stat.test <- compare_means(
 Test_Corr_R ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "AntiSac"),
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(92, 100, 110))

AT_Sac <- ggbarplot(diffs, x = "TBI_Non", y = "Percentage", 
          color = "white", fill = "TBI_Non", palette = myCols3, alpha = 0.7,
          width=0.9,
          order = c("Non", "Short", "Long"),
          ylab = "Percentage correct anti-saccade trials", xlab = " ") + 
          scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
          geom_errorbar(aes(x= TBI_Non, ymin= (lwr.ci*100), ymax = (upr.ci*100)), width=.2, position=position_dodge(.9)) +
          #geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
          theme(legend.position = "none")+
    stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 12)) + 
     theme(axis.title=element_text(size=12)) 
   #labs( subtitle = get_test_label(K_test_Pres, detailed = TRUE))

SacTrialPlots<- ggarrange(PT_Sac , AT_Sac,  labels = c( "A" ,"B"))
ggsave("SacTrialPlots.png", width = 20, height = 10, units = "cm")


```


```{r Sac_Latency, echo=FALSE, message=FALSE, warning=FALSE }
## Pro Sac
K_test_Pres <-  kruskal_test(Saccade_Latency ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "ProSac"))

diffs <- subset(SACdf, TargType_Unity %like% "ProSac") %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Saccade_Latency, na.rm = T), Mean = mean(Saccade_Latency, na.rm = T), SD = sd(Saccade_Latency, na.rm = T))

stat.test <- compare_means(
 Saccade_Latency ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "ProSac"),
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(2000, 2200, 2400))

PL_Sac <- ggplot(subset(SACdf, TargType_Unity %like% "ProSac"), aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   Saccade_Latency, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Pro-saccade latency (ms)")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

## Anti Sac
K_test_Pres <-  kruskal_test(Saccade_Latency ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "AntiSac"))

diffs <- subset(SACdf, TargType_Unity %like% "AntiSac") %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Saccade_Latency, na.rm = T), Mean = mean(Saccade_Latency, na.rm = T), SD = sd(Saccade_Latency, na.rm = T))
stat.test <- compare_means(
 Saccade_Latency ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "AntiSac"),
 method = "wilcox.test"#, p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(2000, 2200, 2400))

AL_Sac <- ggplot(subset(SACdf, TargType_Unity %like% "Anti"), aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   Saccade_Latency, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Anti-saccade latency (ms)")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

```

```{r Sac_Vel, echo=FALSE, message=FALSE, warning=FALSE }
## Pro Sac

K_test_Pres <-  kruskal_test(Saccade_Vel_Deg_s ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "ProSac"))

diffs <- subset(SACdf, TargType_Unity %like% "ProSac") %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Saccade_Vel_Deg_s, na.rm = T), Mean = mean(Saccade_Vel_Deg_s, na.rm = T), SD = sd(Saccade_Vel_Deg_s, na.rm = T))

stat.test <- compare_means(
 Saccade_Vel_Deg_s ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "ProSac"),
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(300, 320, 350))

PV_Sac <- ggplot(subset(SACdf, TargType_Unity %like% "ProSac"), aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   Saccade_Vel_Deg_s, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Pro-saccade velocity (degrees/s)")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 


## Anti Sac
K_test_Pres <-  kruskal_test(Saccade_Vel_Deg_s ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "AntiSac"))

diffs <- subset(SACdf, TargType_Unity %like% "AntiSac") %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Saccade_Vel_Deg_s, na.rm = T), Mean = mean(Saccade_Vel_Deg_s, na.rm = T), SD = sd(Saccade_Vel_Deg_s, na.rm = T))

stat.test <- compare_means(
 Saccade_Vel_Deg_s ~ TBI_Non, data = subset(SACdf, TargType_Unity %like% "AntiSac"),
 method = "wilcox.test"#, p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(300, 320, 350))

AV_Sac <- ggplot(subset(SACdf, TargType_Unity %like% "Anti"), aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   Saccade_Vel_Deg_s, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Anti-saccade velocity (degrees/s)")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

Sac_LV_Plots<- ggarrange(PL_Sac , AL_Sac, PV_Sac , AV_Sac, nrow=2, ncol=2, labels = c( "A" ,"B", "C" ,"D"))
ggsave("Sac_LV_Plots.png", width = 20, height = 20, units = "cm")

```

## Stroop

```{r StrData, echo=FALSE, message=FALSE, warning=FALSE}
load("Str_Healthy.Rda")
load("Str_ShortTerm.Rda")
load("Str_LongTerm.Rda")

#view(Str_Healthy)
#view(Str_ShortTerm)
#view(Str_LongTerm)

Str_Healthy$ID <- paste(Str_Healthy$ID, 1, sep = "_")
Str_ShortTerm$ID <- paste(Str_ShortTerm$ID, 2, sep = "_")
Str_ShortTerm <- Str_ShortTerm[-c(9)]
Str_LongTerm$ID <- paste(Str_LongTerm$ID, 3, sep = "_")

STRdf <- rbind(Str_Healthy, Str_ShortTerm, Str_LongTerm)

STRdf$Saccade_Latency <- replace(STRdf$Saccade_Latency, STRdf$Saccade_Latency < 60, NA)

STRdf$Test_Corr <-  as.numeric(STRdf$Test_Corr)
save(STRdf,file="STRdf.Rda")



leveneTest(Test_Corr ~ Pre_Post,       STRdf)
leveneTest(Saccade_Latency ~ Pre_Post, STRdf) 
leveneTest(trialTime ~ Pre_Post,       STRdf)


shapiro.test(STRdf$Test_Corr)
shapiro.test(STRdf$Saccade_Latency)
shapiro.test(STRdf$trialTime)


colNames <- c("ID","Trial Number", "Stroop Part" , "Saccade Latency (ms)", "Trial Time (s)", "Number Trials Correct", "Pre_Post", "TBI_Non")
testTitle <- "Summary Data for Stroop"
source("GetSummaryTables.R")
GetSummaryTablesCIs(STRdf, colNames, testTitle) 
```


```{r Str_Trials Corr, echo=FALSE, message=FALSE, warning=FALSE }
## Part one
K_test_Pres <-  kruskal_test(Test_Corr ~ TBI_Non, data = subset(STRdf, strpPart_Unity == 1))


diffs <- subset(STRdf, strpPart_Unity == 1) %>% group_by(TBI_Non) %>%
  dplyr::summarise(Tot = sum(Test_Corr, na.rm = T), Medians = median(Test_Corr, na.rm = T), Mean = mean(Test_Corr, na.rm = T), Percentage=(mean(Test_Corr, na.rm = T)*100), SD = sd(Test_Corr, na.rm = T), Num = n(), CorrSE = SD/115)

library("DescTools") # This package masks %like% detatch after use
BinomCI1 <- BinomCI(x=diffs$Tot, n=diffs$Num, method="jeffreys", sides="two.sided")
diffs <- cbind(diffs, BinomCI1)
#detach("package:DescTools")


stat.test <- compare_means(
 Test_Corr ~ TBI_Non, data = subset(STRdf, strpPart_Unity == 1),
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c( 100, 110, 120))

P1_Sac <- ggbarplot(diffs, x = "TBI_Non", y = "Percentage", 
          color = "white", fill = "TBI_Non", palette = myCols3, alpha = 0.7,
          width=0.9,
          order = c("Non", "Short", "Long"),
          ylab = "Percentage correct part one trials", xlab = " ") + 
          scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  geom_errorbar(aes(x= TBI_Non, ymin= (lwr.ci*100), ymax = (upr.ci*100)), width=.2, position=position_dodge(.9)) +
          theme(legend.position = "none")+
    stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) +
  scale_y_continuous(breaks=c(0, 25, 50, 75, 100))
   #labs( subtitle = get_test_label(K_test_Pres, detailed = TRUE))


## Part 2
K_test_Pres <-  kruskal_test(Test_Corr ~ TBI_Non, data = subset(STRdf, strpPart_Unity == 2))

diffs <- subset(STRdf, strpPart_Unity == 2) %>% group_by(TBI_Non) %>%
  dplyr::summarise(Tot = sum(Test_Corr, na.rm = T), Medians = median(Test_Corr, na.rm = T), Mean = mean(Test_Corr, na.rm = T), Percentage=(mean(Test_Corr, na.rm = T)*100), SD = sd(Test_Corr, na.rm = T), Num = n(), CorrSE = SD/115)

library("DescTools") # This package masks %like% detatch after use
BinomCI1 <- BinomCI(x=diffs$Tot, n=diffs$Num, method="jeffreys", sides="two.sided")
diffs <- cbind(diffs, BinomCI1)
detach("package:DescTools")

stat.test <- compare_means(
 Test_Corr ~ TBI_Non, data = subset(STRdf, strpPart_Unity == 2),
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(100, 110, 120))

P2_Sac <- ggbarplot(diffs, x = "TBI_Non", y = "Percentage", 
          color = "white", fill = "TBI_Non", palette = myCols3, alpha = 0.7,
          width=0.9,
          order = c("Non", "Short", "Long"),
          ylab = "Percentage correct part two trials", xlab = " ") + 
          scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
          geom_errorbar(aes(x= TBI_Non, ymin=(lwr.ci*100), ymax = (upr.ci*100)), width=.2, position=position_dodge(.9)) +
          #geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
          theme(legend.position = "none")+
    stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) +
  scale_y_continuous(breaks=c(0, 25, 50, 75, 100))

StrTrialPlots<- ggarrange(P1_Sac , P2_Sac,  labels = c( "A" ,"B"))
ggsave("StrTrialPlots.png", width = 20, height = 10, units = "cm")

```

```{r Str_Trial Time, echo=FALSE, message=FALSE, warning=FALSE }
## P1
P1 <- subset(STRdf, strpPart_Unity == 1)
P1 <- P1[c(1,5,8)]
P1_totalTime <- P1 %>% unite(ID, ID, TBI_Non, sep = "_")

DT <- data.table(P1_totalTime)
P1_tots <- setnames(DT[, sapply(.SD, function(x)  list(tot=sum(x, na.rm = T))), by=ID], c("ID", sapply(names(DT)[-1], paste0, c(".tot"))))
P1_tots <-  P1_tots %>% separate(ID, c("ID", "group", "TBI_Non"))
P1_tots <- P1_tots %>% unite(ID, ID, group, sep = "_")

K_test_Pres <-  kruskal_test(trialTime.tot ~ TBI_Non, data = P1_tots)
diffs <- P1_tots %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(trialTime.tot, na.rm = T), Mean = mean(trialTime.tot, na.rm = T), SD = sd(trialTime.tot, na.rm = T),  CorrSE = SD/115)

stat.test <- compare_means(
 trialTime.tot ~ TBI_Non, data = P1_tots,
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(35,40,45))

TT1_Str <- ggplot(P1_tots, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = trialTime.tot, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Part one total test time (s)")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

## P2
P2 <- subset(STRdf, strpPart_Unity == 2)
P2 <- P2[c(1,5,8)]
P2_totalTime <- P2 %>% unite(ID, ID, TBI_Non, sep = "_")

DT <- data.table(P2_totalTime)
P2_tots <- setnames(DT[, sapply(.SD, function(x)  list(tot=sum(x, na.rm = T))), by=ID], c("ID", sapply(names(DT)[-1], paste0, c(".tot"))))
P2_tots <-  P2_tots %>% separate(ID, c("ID", "group", "TBI_Non"))
P2_tots <- P2_tots %>% unite(ID, ID, group, sep = "_")

K_test_Pres <-  kruskal_test(trialTime.tot ~ TBI_Non, data = P2_tots)
diffs <- P2_tots %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(trialTime.tot, na.rm = T), Mean = mean(trialTime.tot, na.rm = T), SD = sd(trialTime.tot, na.rm = T),  CorrSE = SD/115)

stat.test <- compare_means(
 trialTime.tot ~ TBI_Non, data = P2_tots,
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(35,40,45))

TT2_Str <- ggplot(P2_tots, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = trialTime.tot, color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Part two total test time (s)")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

```

```{r Sac_Latency, echo=FALSE, message=FALSE, warning=FALSE }
## Pro Sac

K_test_Pres <-  kruskal_test(Saccade_Latency ~ TBI_Non, data = subset(STRdf, strpPart_Unity == 1))

diffs <- subset(STRdf, strpPart_Unity == 1) %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Saccade_Latency, na.rm = T), Mean = mean(Saccade_Latency, na.rm = T), SD = sd(Saccade_Latency, na.rm = T),  CorrSE = SD/115)

stat.test <- compare_means(
 Saccade_Latency ~ TBI_Non, data = subset(STRdf, strpPart_Unity == 1),
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(log10(2000), log10(3000), log10(5000)))

P1_Str <- ggplot(subset(STRdf, strpPart_Unity == 1), aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   log10(Saccade_Latency), color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Part one latency log (ms)")+ 
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 




## Anti Sac

K_test_Pres <-  kruskal_test(Saccade_Latency ~ TBI_Non, data = subset(STRdf, strpPart_Unity == 2))

diffs <- subset(STRdf, strpPart_Unity == 2) %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Saccade_Latency, na.rm = T), Mean = mean(Saccade_Latency, na.rm = T), SD = sd(Saccade_Latency, na.rm = T),  CorrSE = SD/115)

stat.test <- compare_means(
 Saccade_Latency ~ TBI_Non, data = subset(STRdf, strpPart_Unity == 2),
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(log10(2000), log10(3000), log10(5000)))

P2_Str <- ggplot(subset(STRdf, strpPart_Unity == 2), aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y =   log10(Saccade_Latency), color =  TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Part two latency log (ms)")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

StrTimeLatPlots<- ggarrange(P1_Str , P2_Str, TT1_Str, TT2_Str, nrow=2, ncol=2,  labels = c( "A" ,"B", "C", "D"))
ggsave("StrTimeLatPlots.png", width = 20, height = 20, units = "cm")

```

## VOR

```{r VORData, echo=FALSE, message=FALSE, warning=FALSE}
load("VOR_Healthy.Rda")
load("Vor_ShortTerm.Rda")
load("VOR_LongTerm.Rda")

view(VOR_Healthy)
view(Vor_ShortTerm)
view(VOR_LongTerm)

VOR_Healthy$ID <- paste(VOR_Healthy$ID, 1, sep = "_")
#VOR_Healthy <- VOR_Healthy[-c(7)]
Vor_ShortTerm$ID <- paste(Vor_ShortTerm$ID, 2, sep = "_")
VOR_LongTerm$ID <- paste(VOR_LongTerm$ID, 3, sep = "_")

#VOR_Healthy$Time_Max_Gain <- VOR_Healthy$Time_Max_Gain * 1000
#Vor_ShortTerm$Time_Max_Gain <- Vor_ShortTerm$Time_Max_Gain * 1000


VORdf <- rbind(VOR_Healthy, Vor_ShortTerm, VOR_LongTerm)
save(VORdf,file="VORdf.Rda")

# percental horzont saccs
r_Full <- nrow(VORdf)
n_H_Sac <- nrow(subset(VORdf, Horiz_Saccade_Number >= 1))
N_Hor_Sac <- (n_H_Sac/r_Full)*100
N_Hor_Sac
# percental vert saccs
n_V_Sac <- nrow(subset(VORdf, Vert_Saccade_Number >= 1))
N_Ver_Sac <- (n_V_Sac/r_Full)*100
N_Ver_Sac


leveneTest(Gain ~ Pre_Post,       VORdf)
leveneTest(Time_Max_Gain ~ Pre_Post, VORdf) 
leveneTest(HVA_Mean_deg ~ Pre_Post,       VORdf)
leveneTest(VVA_Mean_deg ~ Pre_Post,       VORdf)
leveneTest(Horiz_Saccade_Number ~ Pre_Post, VORdf) 
leveneTest(Vert_Saccade_Number ~ Pre_Post,       VORdf)
leveneTest(BCEA_68_Log10 ~ Pre_Post,       VORdf)


shapiro.test(VORdf$Gain)
shapiro.test(VORdf$Time_Max_Gain)
shapiro.test(VORdf$HVA_Mean_deg)
shapiro.test(VORdf$VVA_Mean_deg)
shapiro.test(VORdf$Horiz_Saccade_Number)
shapiro.test(VORdf$Vert_Saccade_Number)
shapiro.test(VORdf$BCEA_68_Log10)

colnames(VORdf)
colNames <- c("ID", "Trial Number", "Gain", "Time to Maximum Gain (ms)","Horizontal Visual Angle Error (deg)", "Vertical Visual Angle Error (deg)",  "Number Horizontal Saccades", "Number Vertical Saccades","BCEA Log10 (MinArc2)" ,"Pre_Post", "TBI_Non")
testTitle <- "Summary Data for VOR"
source("GetSummaryTables.R")
GetSummaryTablesCIs(VORdf, colNames, testTitle) 
```

```{r VOR_BCEA, echo=FALSE, message=FALSE, warning=FALSE }
# difference bw Pre groups
K_test_Pres <-  kruskal.test(BCEA_68_Log10 ~ TBI_Non, data = VORdf)
diffs <- VORdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(BCEA_68_Log10, na.rm = T), Mean = mean(BCEA_68_Log10, na.rm = T), SD = sd(BCEA_68_Log10, na.rm = T))

stat.test <- compare_means(
 BCEA_68_Log10 ~ TBI_Non, data = VORdf,
 method = "t.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(6,6.5,7.1))

test <-  expression("BCEA log"[10]* " (minarc"^2*")")
my_title <- parse(text=test)

B_VOR <- ggplot(VORdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = BCEA_68_Log10, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab(my_title)+
  #geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

```


```{r VOR_HVA, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(HVA_Mean_deg ~ TBI_Non, data = VORdf)
diffs <- VORdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(HVA_Mean_deg, na.rm = T), Mean = mean(HVA_Mean_deg, na.rm = T), SD = sd(HVA_Mean_deg, na.rm = T))

stat.test <- compare_means(
 HVA_Mean_deg ~ TBI_Non, data = VORdf,
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(3,4.5,6))

H_VOR <- ggplot(VORdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = HVA_Mean_deg, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Horizontal visual angle error (degrees)")+
  geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14))  + ylim(-6, 6) 

```


```{r VOR_VVA, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(VVA_Mean_deg ~ TBI_Non, data = VORdf)
diffs <- VORdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(VVA_Mean_deg, na.rm = T), Mean = mean(VVA_Mean_deg, na.rm = T), SD = sd(VVA_Mean_deg, na.rm = T))

stat.test <- compare_means(
 VVA_Mean_deg ~ TBI_Non, data = VORdf,
 method = "t.test"#, p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(2,2.5,3.2))

V_VOR <- ggplot(VORdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = VVA_Mean_deg, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Vertical visual angle error (degrees)")+
  geom_hline(yintercept=0, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

VORPlotsVA <- ggarrange(B_VOR, NULL, H_VOR, V_VOR,  labels = c( "A" , "", "B", "C"))
ggsave("VORPlotsVA.png", width = 20, height = 22, units = "cm")

```

```{r VOR_Gain, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(Gain ~ TBI_Non, data = VORdf)
diffs <- VORdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Gain, na.rm = T), Mean = mean(Gain, na.rm = T), SD = sd(Gain, na.rm = T))

stat.test <- compare_means(
 Gain ~ TBI_Non, data = VORdf,
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(1.02,1.05,1.08))

G_VOR <- ggplot(VORdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = Gain, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Gain")+
  geom_hline(yintercept=1, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

VORPlotsBCEAGain <- ggarrange(B_VOR, G_VOR,  labels = c( "A" ,  "B"))
ggsave("VORPlotsBCEAGain.png", width = 20, height = 13, units = "cm")

```

```{r VOR_TimeGain, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(Time_Max_Gain ~ TBI_Non, data = VORdf)
diffs <- VORdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Time_Max_Gain, na.rm = T), Mean = mean(Time_Max_Gain, na.rm = T), SD = sd(Time_Max_Gain, na.rm = T))

stat.test <- compare_means(
 Time_Max_Gain ~ TBI_Non, data = VORdf,
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(550, 700, 880))

TG_VOR <- ggplot(VORdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = Time_Max_Gain, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, position=position_jitter(0.2), alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Time to maximum gain (ms)")+
  #geom_hline(yintercept=1, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 

```

```{r VOR_HS, echo=FALSE, message=FALSE, warning=FALSE }
K_test_Pres <-  kruskal.test(Horiz_Saccade_Number ~ TBI_Non, data = VORdf)
diffs <- VORdf %>% group_by(TBI_Non) %>%
  dplyr::summarise(Medians = median(Horiz_Saccade_Number, na.rm = T), Mean = mean(Horiz_Saccade_Number, na.rm = T), SD = sd(Horiz_Saccade_Number, na.rm = T))

stat.test <- compare_means(
 Horiz_Saccade_Number ~ TBI_Non, data = VORdf,
 method = "wilcox.test", p.adjust.method = "holm"
)
stat.test <- stat.test %>%
 mutate(y.position = c(4,4.5,5))

HS_VOR <- ggplot(VORdf, aes(x = factor(TBI_Non, levels = c("Non", "Short", "Long")), y = Horiz_Saccade_Number, color = TBI_Non)) + 
  geom_boxplot(outlier.shape = NA)+ 
  geom_jitter(shape=16, width=0.1, height=0, alpha=0.4)+
  scale_color_manual(values=c( "#D55E00", "#56B4E9", "#009E73")) +
  scale_x_discrete(labels=c("Control","mTBI","PPCS")) +
  theme_classic() + theme(legend.position="none")+
  xlab(" ") + ylab("Number of horizontal saccades")+
  #geom_hline(yintercept=1, linetype="dashed", color="#5f6061")+
  stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) 



Control  <- subset(VORdf, TBI_Non %like% "Non")
Control  <- Control$Horiz_Saccade_Number
Control <- as.data.frame(table(Control))
Control$Non <- (Control$Freq / sum(Control$Freq))*100
mTBI <- subset(VORdf,  TBI_Non %like% "Short")
mTBI <-  mTBI$Horiz_Saccade_Number
mTBI <- as.data.frame(table(mTBI))
mTBI$Short <- (mTBI$Freq / sum(mTBI$Freq))*100  
PPCS  <- subset(VORdf,  TBI_Non %like% "Long")
PPCS  <- PPCS$Horiz_Saccade_Number
PPCS <- as.data.frame(table(PPCS))
PPCS$Long <- (PPCS$Freq / sum(PPCS$Freq))*100 


Outcome_Change <- qpcR:::cbind.na(Control, mTBI, PPCS)
Outcome_Change <- as.data.frame(Outcome_Change)
Outcome_ChangeG <- Outcome_Change %>% gather(State, NumberS, 3,6,9)
Outcome_ChangeG$NumberS[is.na(Outcome_ChangeG$NumberS)]<-0
#Outcome_ChangeG$NumberS <- round(Outcome_ChangeG$NumberS, 0)
Outcome_ChangeG$Count <- seq(0,5, by=1)

myColsLightDark <- c("#D55E00","#f2b483", "#56B4E9", "#aad8f2")

myColsLightDark <- c( 'darkorange','#f2b483', 'dodgerblue', '#aad8f2')

myCols6 <- c(  'dodgerblue','#aad8f2', '#64d40b','#b8f587' ,'#f2b483','darkorange')

myCols9 <- c("red", '#9d2ef2', 'blue', 'dodgerblue','#aad8f2', '#64d40b','#b8f587' ,'#f2b483','darkorange')

Outcome_ChangeG$TBI_Non <- as.factor(Outcome_ChangeG$State)
Outcome_ChangeG$Count <- as.factor(Outcome_ChangeG$Count)

Outcome_ChangeG <- Outcome_ChangeG[c(8,9, 10)]


stat.test$Count <- as.factor(0)
stat.test <- stat.test %>%
 mutate(y.position = c(112,124, 136))
Pur_Stacked <- ggplot(Outcome_ChangeG , aes( y=NumberS, x=TBI_Non,fill=fct_rev(Count))) + 
    geom_bar( stat="identity")+
  theme_classic() + xlab("") + ylab("Percentage") + guides(fill = guide_legend(reverse = T)) + 
  theme( legend.position = "right") +
  labs(fill = "Number of\nsaccades")  +   scale_fill_manual( values = myCols6) + 
     theme(axis.title=element_text(size=12)) + 
  scale_y_continuous(breaks=seq(0,100,20))+
  scale_x_discrete(limits=c("Non","Short" , "Long" ), labels=c("Non" = "Control", "Short" = "mTBI","Long" = "PPCS" )) + stat_pvalue_manual(stat.test, label = "p = {scales::pvalue(p.adj)}", size = 4) + theme(text = element_text(size = 16)) + 
     theme(axis.title=element_text(size=14)) + theme(legend.title = element_text(size=12))
  
  

VORPlotsG <- ggarrange(G_VOR, TG_VOR,  Pur_Stacked, NULL, labels = c( "A" , "B",  "C", ""))
ggsave("VORPlotsG.png", width = 20, height = 20, units = "cm")

```